# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.campaign:
        class: AppBundle\Admin\CampaignAdmin
        arguments: [~, AppBundle\Entity\Campaign, ~]
        tags:
            - { name: sonata.admin, group: "Campaigns", manager_type: orm, label: Campaign }
    admin.campaignFile:
        class: AppBundle\Admin\CampaignFileAdmin
        arguments: [~, AppBundle\Entity\CampaignFile, ~]
        tags:
            - { name: sonata.admin, group: "Campaigns", manager_type: orm, label: Campaign File }
    #admin.recipient:
    #    class: AppBundle\Admin\RecipientAdmin
    #    arguments: [~, AppBundle\Entity\Recipient, ~]
    #    tags:
    #        - { name: sonata.admin, group: "Campaigns", manager_type: orm, label: Recipient }
    admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, ~]
        tags:
            - { name: sonata.admin, group: "Clients", manager_type: orm, label: Client }
    #admin.kpimonth:
    #    class: AppBundle\Admin\KpiMonthAdmin
    #    arguments: [~, AppBundle\Entity\KpiMonth, ~]
    #    tags:
    #        - { name: sonata.admin, group: "KPIs", manager_type: orm, label: KpiMonth }

    app.init_Kpi_dates:
        class: AppBundle\Service\initKpiFilterDatesService

    cron.import:
        class: AppBundle\Service\ImportCronService
        arguments:
            - %local_ip%
            - @service_container
            - @doctrine.orm.entity_manager
    cron.export:
        class: AppBundle\Service\ExportCronService
        arguments: [ @doctrine.orm.entity_manager ]

    import.file.log:
        class: AppBundle\Service\ImportFileLogService
        arguments: [ @doctrine.orm.entity_manager ]
    app.twig_extension:
        class: AppBundle\Service\TwigExtensionService
        public: false
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: twig.extension }

    app.kpi_filter_session:
        class: AppBundle\Service\KpiFilterSessionService
        arguments:
            - @service_container
            - @doctrine.orm.default_entity_manager
    app.pdo_connect:
        class: AppBundle\Service\PdoService
        arguments: [ @service_container ]