# src/OC/PlatformBundle/Resources/config/routing.yml

#app_home:
#    path:      /home
#    defaults:  { _controller: AppBundle:Home:index}

#app_test:
#    path:      /test
#    defaults:  { _controller: AppBundle:Home:test}

#app_campaigns_index:
#    path:      /campaign
#    defaults:  { _controller: AppBundle:Campaign:index}

#app_campaign_clients_list:
#    path:      /campaign/{campaign_id}
#    defaults:  { _controller: AppBundle:Campaign:viewCampaignClientsList}

#app_campaign_client:
#    path:      /campaign/{campaign_id}/{client_id}
#    defaults:  { _controller: AppBundle:Campaign:viewCampaignClient}

#app_campaign_send_email:
#    path:      /campaign_send_email/{recipient_id}
#    defaults:  { _controller: AppBundle:Campaign:CampaignSendEmail}

app_kpi_month:
    path:      /kpi/m/{user_id}/{month}
    defaults:  { _controller: AppBundle:Kpi:month, month: null}

app_kpi_ytd:
    path:      /kpi/ytd/{user_id}/{year}
    defaults:  { _controller: AppBundle:Kpi:ytd, year: null}

app_kpi_fid:
    path:      /kpi/fid/{user_id}
    defaults:  { _controller: AppBundle:Kpi:fid}

app_kpi_planning:
    path:      /kpi/planning/{user_id}/{month}
    defaults:  { _controller: AppBundle:Kpi:planning, month: null}

app_kpi_faq:
    path:      /kpi/faq/{user_id}
    defaults:  { _controller: AppBundle:Kpi:faq}

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/login
        permanent: true